version: '3'
services:
  api:
    tty: true
    container_name: api
    build: 
      context: ./
      dockerfile: ./python_service/Dockerfile
    depends_on:
      - broker
    ports:
      - "5001:5001"
    volumes:
      - ./:/usr/work_env/
    env_file:
      - ./python_service/service.env

  streamlitapp:
    tty: true
    container_name: streamlitapp
    build: 
      context: ./
      dockerfile: ./python_service/streamlit_app/Dockerfile
    depends_on:
      - broker
    ports:
      - "8051:8051"
    volumes:
      - ./:/usr/work_env/
    env_file:
      - ./python_service/service.env

  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    #build: 
    #  context: ./
    #  dockerfile: ./zookeeper/Dockerfile
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.0.1
    container_name: broker
    ports:
    # To learn about configuring Kafka for access across networks see
    # https://www.confluent.io/blog/kafka-client-cannot-connect-to-broker-on-aws-on-docker-etc/
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1